apiVersion: v1
kind: Service
metadata:
  name: apachewebsite-service
spec:
  selector:
    app: apachewebsite
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
  type: LoadBalancer     # Change to LoadBalancer if using cloud provider
